# Configuration globale
WINDOW_SIZE = "800x600"
BACKGROUND_COLOR = "#FFE4F2"
FRAME_COLOR = "#FF69B4"
BUTTON_COLOR = "white"
BUTTON_TEXT_COLOR = "black"
TITLE_COLOR = "#8B0000"

# Configuration des algorithmes
DEFAULT_VERTEX_SIZE = 500
DEFAULT_EDGE_PROBABILITY = 0.3
MIN_WEIGHT = 1
MAX_WEIGHT = 100

# Configuration du transport
MIN_SUPPLY_DEMAND = 50
MAX_SUPPLY_DEMAND = 200
MIN_COST = 10
MAX_COST = 100